name: Create PR for automated arena push branches

on:
  push:
    branches:
      - "automated-arena-push-*"

permissions:
  contents: write  # Allows push and pull request actions

jobs:
  create_pr_for_automated_push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the commons repository
      - name: Checkout the commons repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch full history for context

      # Step 2: Install GitHub CLI (gh)
      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      # Step 3: Authenticate GitHub CLI using GITHUB_TOKEN
      - name: Authenticate GitHub CLI
        run: gh auth login --with-token <<< "${{ secrets.GITHUB_TOKEN }}"

      # Step 4: Create Pull Request using GitHub CLI
      - name: Create Pull Request
        run: |
          gh pr create -B main -H ${{ github.ref_name }} \
            --title "Automated Sync: Arena repo to Commons repo" \
            --body "This pull request syncs changes from the arena repository into the commons repository. Branch: ${{ github.ref_name }}."
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
