name: Create PR for automated arena push branches

on:
  push:
    branches:
      - "automated-arena-push-**"

permissions:
  contents: write  # Allows pushing and pull request actions

jobs:
  create_pr_for_automated_push:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the commons repository
      - name: Checkout the commons repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Fetch full history for context

      # Step 2: Create Pull Request to main branch if branch name starts with automated-arena-push
      - name: create pull request
        run: gh pr create -B main -H ${{ github.ref_name }} --title 'Merge branch_to_merge into base_branch' --body 'Created by Github action'
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

